### ISSUE TITLE
[question] Updating Resources

### ISSUE THREAD

**Issue by Moezenka** [blakelead/nsinjector#3]
Hi,

Does nsinjector update any previously created resources if any changes are made?

For instance:
Lets say nsinjector deploys a rolebinding whenever a namespace is created.
If i were to modify the rolebinding in the `kind: NamespaceResourcesInjector`, will it re-apply and recreate the rolebinding?

Thanks in advance!

**Comment by blakelead** [comment]
Hi @Moezenka, yes it will.
